### ISSUE TITLE
Platform-dependent error in tester.get.rmse.R

### ISSUE THREAD

**Issue by ArtPoon** [brj1/node.dating#1]
@emvolz-phylodynamics is getting discrepant results from running test script `tester.get.rmse.R` on the simulated data in the repo.  Specifically, he is getting a mean RMSE of about 420, whereas we reported a value of about 29 in the manuscript.  I attempted to reproduce the issue on my Mac and got an RMSE of 29.21 as expected.  However, when I ran the same script and data on an Ubuntu workstation, I got an RMSE of about 426.

**Comment by brj1** [comment]
I think I fixed this in the commit. Was a problem with the way I was matching up the columns of different csv files. It should be verified that it is consistent now.
