### ISSUE TITLE
estimate.dates fails with "replacement has length zero" error

### ISSUE THREAD

**Issue by ArtPoon** [brj1/node.dating#3]
We've determined that the problem arises when calling `solve.cube` with the following arguments:
```R
> c(m, min(dates[ch]))
[1] 2007.183 2007.183
> dates[ch]
[1] 2007.202 2007.183
> ch.edge
[1] 5864 5865
> dates[p]
[1] 2007.183
> p.edge
[1] 5863
> solve.cube(c(m, min(dates[ch])), dates[ch], 
+                      ch.edge, dates[p], p.edge)
Warning in log(tim) : NaNs produced
Warning in log(tim) : NaNs produced
numeric(0)
```

**Comment by brj1** [comment]
Thanks Art. I think that the dimensions of the first two parameters are wrong for solve.cube. estimate.dates is probably calling solve.cube by mistake. I'll look into it.

**Comment by brj1** [comment]
The problem is that the first parameter's values are equal meaning that there is no range to choose from. I'll think about a way to handle this case.

**Comment by brj1** [comment]
I've pushed a version to GitHub that fixes this problem. However if the bounds are are exactly equal node.dating will complain about the likelihood being Infinity; this is intentional.

**Comment by ArtPoon** [comment]
Thanks Brad - would a quick fix be to require a minimum (non-zero) branch length in trees?

**Comment by brj1** [comment]
Indeed. If there are zero-valued branch lengths then the lengths should either be padded (set to 1e-8 say) or the edge should be identified (In the ape version of node.dating it will estimate the date of the node, but in the version on the random branch the node's date can be fixed).
