### ISSUE TITLE
Bug in opt.fun

### ISSUE THREAD

**Issue by Captain-Blackstone** [brj1/node.dating#4]
Hello!
I've used node.dating for my research and encountered weird behavior - some nodes received unrealistically early date. So I've taken a closer look inside the estimate.dates function and I am convinced that I've found a bug. Which I'd like to report. Here I go.
The function calc.Like takes as an input ch.node, ch.edge and x. Inside this function the vector t$edge.length[ch.edge] is calcultaed based on ch.edge value - the length of the edges leading to children nodes, based on the children nodes IDs. But inside the opt.fun function the function calc.Like is called with arguments dates[ch], t$edge.length[ch.edge], x. So, instead of passing ch.edge to calc.Like function, leaving it to calculate t$edge.length[ch.edge] itself, it passes t$edge.length[ch.edge]. There is another call of calc.Like inside opt.fun, and arguments there also need to be fixed in the same manner.
I guess with edge length being expressed as floating point numbers such operation should result in straight up error, but in my case edge lengths were expressed in integers. Because of that opt.fun calculated the lengths of edges, leading to children, used these as IDs for children nodes and inside calc.Like function the length of edges corresponding to these IDs were taken. Needless to say, it's not what I wanted)
Dmitry

**Comment by ArtPoon** [comment]
Hi Dmitry, thanks for the detailed bug report!  I'm pinging @brj1 as package maintainer.

**Comment by brj1** [comment]
Hi Dimity.

Thanks for letting me know about this bug. Since I always use bifurcating trees, I failed to see this error. I've changed the code - you were exactly right about the mistake and the fix. I've pushed the master and the more complicated random branch which both had this error.
